services:
  backend:
    build: ./backend
    container_name: train_controller_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/app:/app/app
    networks:
      - train_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: train_controller_frontend
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
    networks:
      - train_network
    volumes:
      - ./frontend:/app

networks:
  train_network:
    driver: bridge
